name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:14  # Runs within a Node.js 14 container

    steps:
      # Step 1: Check Node.js and npm version
      - name: Check Node and npm version
        run: |
          node --version
          npm --version

      # Step 2: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Set the working directory
      - name: Set working directory
        run: echo "Working directory: $(pwd)"  # This helps debug the current directory structure

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./Release-demo  # Adjust this to the correct path to your package.json

      # Step 5: Run tests (optional)
      - name: Run tests
        run: npm test
        working-directory: ./Release-demo  # Adjust this to the correct path if needed

      # Step 6: Build the project
      - name: Build the project
        run: npm run build
        working-directory: ./Release-demo  # Adjust this to the correct path if needed


