name: Create or Update Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Create or Update Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v1

      - name: Create or Update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          if gh release view "$TAG" > /dev/null 2>&1; then
            echo "Release with tag $TAG already exists, updating release."
            gh release edit "$TAG" \
              --title "${TAG#v}" \
              --generate-notes
          else
            echo "Creating new release with tag $TAG."
            gh release create "$TAG" \
              --title "${TAG#v}" \
              --generate-notes
          fi

