name: Run Selenium Tests and Create Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest  # Using Selenium Chrome standalone service
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt includes selenium and pytest
          
      - name: Check Docker version
        run: docker --version
        
      - name: Build Docker image
        run: |
          docker build -t my-selenium-app:latest .  # Build the Docker image
          
      - name: Save Docker image
        run: docker image save my-selenium-app:latest | xz -z -e -7 -T0 > image.xz  # Save the Docker image in compressed form
        
      - name: List Files
        run: ls -la  # Verify that selenium.xz was created
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}  # Use the run number as the version tag
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available in Actions
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: image.xz  # Path to the compressed Docker image
          asset_name: image.xz
          asset_content_type: application/x-xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selenium tests
        run: |
          pytest -v > test_results.log  
            
      - name: Display test results log
        run: cat test_results.log  # Output the test result log to GitHub Actions console
  
      - name: Archive test results
        uses: actions/upload-artifact@v3  # Upload the test results log as an artifact
        with:
          name: test-results-log
          path: test_results.log
          
      