name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Navigate to frontend directory if your package.json is not in the root
      - name: Navigate to frontend directory
        run: cd frontend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend  # Use working-directory if package.json is inside frontend directory

      # Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend  # Specify the working directory


