name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:14  # Runs within a Node.js 14 container

    steps:
      # Step 1: Check Node.js and npm version
      - name: Check Node and npm version
        run: |
          node --version
          npm --version

      # Step 2: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Set up Node.js (optional, since you're using container-based)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can remove or adjust this if you're using a specific container

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./Release-demo/Release-demo  # Adjust this directory if needed

      # Step 5: Run tests (optional)
      - name: Run tests
        run: npm test
        working-directory: ./Release-demo/Release-demo  # Adjust this directory if needed

      # Step 6: Build the project
      - name: Build the project
        run: npm run build
        working-directory: ./Release-demo/Release-demo  # Adjust this directory if needed

