name: WebTest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up job"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a `requirements.txt` file

    - name: Run WebTest
      run: |
        # Replace with the actual path if `webtest.py` is in a subfolder
        python webtest.py
    
    - name: Save screenshots
      if: success() || failure()
      run: |
        mkdir -p screenshots
        cp *.png screenshots/
        echo "Screenshots saved"

    - name: Post Set up Python
      run: echo "Python set up completed"

    - name: Stop containers
      run: echo "Stopping containers" # Only applicable if you're using containers

    - name: Complete job
      run: echo "Job complete"


