name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          python -m unittest discover -s tests
