name: WebTest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up job"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies if requirements.txt exists
    - name: Install dependencies
      run: |
        if [ -f "requirements.txt" ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping dependency installation"
        fi

    - name: Run WebTest
      run: |
        # Adjust the path to where webtest.py is located if needed
        if [ -f "webtest.py" ]; then
          python webtest.py
        else
          echo "webtest.py not found, skipping tests"
        fi
    
    - name: Save screenshots
      if: always()  # This will run regardless of success or failure of the previous step
      run: |
        if ls *.png 1> /dev/null 2>&1; then
          mkdir -p screenshots
          cp *.png screenshots/
          echo "Screenshots saved"
        else
          echo "No screenshots to save"
        fi

    - name: Post Set up Python
      run: echo "Python set up completed"

    - name: Stop containers
      run: echo "Stopping containers" # Only applicable if you're using containers

    - name: Complete job
      run: echo "Job complete"
